// <auto-generated />
namespace WpfLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class PersonChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PersonChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201912012136165_PersonChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
